services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_PORT=5678
      - TZ=America/Toronto
      - GENERIC_TIMEZONE=America/Toronto

      - N8N_SECURE_COOKIE=true
      - N8N_PROTOCOL=http
      - N8N_PATH=/n8n
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:

