services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    ports: ["5678:5678"]
    environment:
      - N8N_HOST=<your-hostname>.ts.net   # optional, helps with webhooks
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - TZ=America/Toronto
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data:

